export type Bundle = { hz: boolean; perf: boolean; dnd: boolean; rot: boolean; guard: boolean; bright: boolean; awake: boolean };
export type BundleKey = keyof Bundle;
export type Preset = { id: string; name: string; bundle: Bundle };
export type Stretch = { on: boolean; mode: 'ratio' | 'custom'; ratio: string; w: number; h: number };
export type Script = { id: string; name: string; code: string; trigger: 'start' | 'exit' | 'boot'; pkg: string; on: boolean };
export type Profile = { pkg: string; name: string; dpi: number; auto: boolean; restore: boolean; presetId: string; bundle: Bundle; stretch?: Stretch };
export type LogEntry = { id: string; pkg?: string; title: string; sub: string; at: number };
export type AppState = {
  themeId: string;
  defaultDpi: number;
  automation: boolean;
  restoreOnBoot: boolean;
  lowBattery: boolean;
  lowBatteryPercent: number;
  floating: 'off' | 'gaming' | 'always';
  autoReconnect: boolean;
  mode: 'wireless' | 'root';
  scripts: Script[];
  quick: number[];
  presets: Preset[];
  profiles: Profile[];
  log: LogEntry[];
  flags: { quickNotif: boolean; breakReminder: boolean; chargerPresets: boolean; restoreOnLoss: boolean; intents: boolean; tile: boolean };
};
